# Generated by Django 4.2.16 on 2024-10-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mincontent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
