# Generated by Django 4.2.16 on 2024-11-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_slides_file_testresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
