# Generated by Django 4.2.16 on 2024-11-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidesPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='uploads/pdf')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
