# Generated by Django 4.2.23 on 2025-06-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_articlepdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='uploads/videolessons')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
