# Generated by Django 4.2.27 on 2026-01-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_innovativeschemepdf_subjectinfopdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
