# Generated by Django 4.2.27 on 2026-01-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_usersettings_email_usersettings_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPlotExampleDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Video nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('video', models.FileField(upload_to='uploads/default_videos/custom_plot/', verbose_name='Video fayl')),
                ('epsilon', models.FloatField(default=1.0, verbose_name='Epsilon qiymati')),
                ('x_end', models.IntegerField(default=20, verbose_name='X oxiri')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Yuklangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'CustomPlotExample Default Video',
                'verbose_name_plural': 'CustomPlotExample Default Videolar',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LimitGraphDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Video nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('video', models.FileField(upload_to='uploads/default_videos/limit_graph/', verbose_name='Video fayl')),
                ('epsilon', models.FloatField(default=0.5, verbose_name='Epsilon qiymati')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Yuklangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'LimitGraph Default Video',
                'verbose_name_plural': 'LimitGraph Default Videolar',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
